<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <None Include="..\README.md"
              Pack="true"
              PackagePath="\"/>
    </ItemGroup>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <PackageId>CCAT.Gacha.InventoryManager</PackageId>

        <Authors>MM</Authors>
        <PackageDescription>Inventory System</PackageDescription>
        <Description>Inventory System.</Description>
        <RepositoryUrl>https://github.com/markm001/inventory-manager</RepositoryUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>

        <Title>CCAT.Common.InventoryManager</Title>
    </PropertyGroup>

</Project>
